services:
  reminder-bot:
    container_name: reminder-bot
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/app/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
